kind load docker-image ghcr.io/dexidp/dex:v2.27.0 --name kind
kind load docker-image quay.io/argoproj/argocd:v2.0.3 --name kind
kind load docker-image redis:6.2.1-alpine --name kind
kind load docker-image alpine:3.8 --name kind
kind load docker-image docker.io/bitnami/keycloak:13.0.1-debian-10-r18 --name kind
kind load docker-image docker.io/bitnami/postgresql:11.12.0-debian-10-r23 --name kind
kind load docker-image quay.io/oauth2-proxy/oauth2-proxy:v7.1.3 --name kind
kind load docker-image quay.io/jetstack/cert-manager-controller:v1.4.0 --name kind
kind load docker-image quay.io/jetstack/cert-manager-webhook:v1.4.0 --name kind
kind load docker-image docker.io/bitnami/kube-state-metrics:2.1.0-debian-10-r0 --name kind
kind load docker-image bitnami/kube-state-metrics:2.1.0-debian-10-r0 --name kind
kind load docker-image k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2 --name kind
kind load docker-image docker.io/istio/operator:1.10.1 --name kind
kind load docker-image istio/operator:1.10.1 --name kind
kind load docker-image docker.io/istio/pilot:1.10.1 --name kind
kind load docker-image istio/pilot:1.10.1 --name kind
kind load docker-image quay.io/bitnami/sealed-secrets-controller:v0.16.0 --name kind
kind load docker-image gcr.io/ml-pipeline/cache-deployer:1.6.0 --name kind
kind load docker-image gcr.io/ml-pipeline/cache-server:1.6.0 --name kind
kind load docker-image public.ecr.aws/j1r0q0g6/notebooks/central-dashboard:v1.3.0 --name kind
kind load docker-image public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app:v1.3.0 --name kind
kind load docker-image kubeflowkatib/katib-controller:v0.11.1 --name kind
kind load docker-image docker.io/kubeflowkatib/katib-db-manager:v0.11.1 --name kind
kind load docker-image mysql:8 --name kind
kind load docker-image docker.io/kubeflowkatib/katib-new-ui:v0.11.1 --name kind
kind load docker-image kubeflowkatib/katib-new-ui:v0.11.1 --name kind
kind load docker-image python:3.7 --name kind
kind load docker-image metacontroller/metacontroller:v0.3.0 --name kind
kind load docker-image gcr.io/ml-pipeline/metadata-envoy:1.6.0 --name kind
kind load docker-image gcr.io/tfx-oss-public/ml_metadata_store_server:0.30.0 --name kind
kind load docker-image gcr.io/ml-pipeline/metadata-writer:1.6.0 --name kind
kind load docker-image gcr.io/ml-pipeline/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance --name kind
kind load docker-image gcr.io/ml-pipeline/api-server:1.6.0 --name kind
kind load docker-image gcr.io/ml-pipeline/persistenceagent:1.6.0 --name kind
kind load docker-image gcr.io/ml-pipeline/scheduledworkflow:1.6.0 --name kind
kind load docker-image gcr.io/ml-pipeline/frontend:1.6.0 --name kind
kind load docker-image gcr.io/ml-pipeline/viewer-crd-controller:1.6.0 --name kind
kind load docker-image gcr.io/ml-pipeline/visualization-server:1.6.0 --name kind
kind load docker-image mpioperator/mpi-operator:latest --name kind
kind load docker-image kubeflow/mxnet-operator:v1.1.0 --name kind
kind load docker-image gcr.io/ml-pipeline/mysql:5.7 --name kind
kind load docker-image public.ecr.aws/j1r0q0g6/notebooks/notebook-controller:v1.3.0 --name kind
kind load docker-image public.ecr.aws/j1r0q0g6/notebooks/access-management:v1.3.0 --name kind
kind load docker-image public.ecr.aws/j1r0q0g6/notebooks/profile-controller:v1.3.0 --name kind
kind load docker-image gcr.io/kubeflow-images-public/pytorch-operator:vmaster-g518f9c76 --name kind
kind load docker-image public.ecr.aws/j1r0q0g6/notebooks/tensorboard-controller:master-18264c8f --name kind
kind load docker-image gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0 --name kind
kind load docker-image public.ecr.aws/j1r0q0g6/notebooks/tensorboards-web-app:v1.3.0 --name kind
kind load docker-image public.ecr.aws/j1r0q0g6/training/tf-operator:cd2fc1ff397b1f349f68524f4abd5013a32e3033 --name kind
kind load docker-image public.ecr.aws/j1r0q0g6/notebooks/volumes-web-app:v1.3.0 --name kind
kind load docker-image gcr.io/ml-pipeline/workflow-controller:v2.12.9-license-compliance --name kind
kind load docker-image docker.io/istio/proxyv2:1.10.1 --name kind
kind load docker-image istio/proxyv2:1.10.1 --name kind
kind load docker-image kubeflow/xgboost-operator:v0.2.0 --name kind
