apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radosgw-ingressgateway-certs
  namespace: rook-ceph
spec:
  secretName: radosgw-ingressgateway-certs
  issuerRef:
    name: gateways-issuer
    kind: ClusterIssuer
  commonName: rgw.jutopia-kubeflow.linecorp.com
  dnsNames:
    - rgw.jutopia-kubeflow.linecorp.com
    - '*.rgw.jutopia-kubeflow.linecorp.com'
