kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    postgresql-password: AgB09/LBgyYiIuUkS+DdMOdKrZtRDDnGk6s8pREP7wWV63yhw0CWYeTzlMoigkBtntnNyqH9ghWLiagm3YTWZHs8kpqomZDmUV3EMGfhKD0J+deGIjMzqKXAHp7eNzD+2kQD2R9x0IMrDqXJlhQznGYY0bxApPkm5HMGMtqpdcl+Ix0QcpbPxqYdBAMO4yI5EDvue9HYXvI0+NVSQ2yhbxjEe0MrFiONYJyRqy7XRAifNeIT+x/ZuknmLE2zpsxfY9XESP+SHViZPkJWNAFl0delN+oeMzEsmEp3Xvpk0nOBjyW7oR1+w/mI9QzcukrDgM8VC8x6LG4evfS50hB9u3cqXLd6U8Quf16knozFUdJlfIT9DJW2/xSQ/+74P8sIIZJAmcq6ONz34zkYiozf2kT0YPtyrYC8tZfIKkUHQEGxIT1lwdymJiQjimuaXfF6+dIkHyxrAholddIz8RlVPtQTgF8zjUmGgXZlXcFOjoCqbOc/u7Y/RpFeyh/cm1yZaPx6/dgySNRGVcBFMEBhgb8YfaTD6FGPE0U68N1MS/Cy/rEIxvewVqthjVHloG+K6V92gpdG0pjrVWvehx5b/a/nEHP8avM+0bb4z0CnuQwYIIzdbgHNIYh9CA0X3YO6PfvsgPnj6fVFvsY0B9E8uvKGjAbbghhX4pUhEcDPMjNhEM6FM3vPGD+Id4zBNlk2Ua1EaNxs8B59u9zGfZ21nnvSYc0gr/uKJDr/6lnlHwh44A==
    postgresql-postgres-password: AgA07LwFv4fc4y0DTPU99xiy6JzmO15dwo8JfFh7zY1JBUWBz/Xj3KPxWOUEQUQmN+biV+Wb3Qf7SBTZ4MhNtWokEBuVjAyK+0Ldey67cBQ4acXD7VuPUMkeDf7iVbsTGgtWe8VqrltER477aZwyHOjiCHYooyLu/wNrJcX6yoKxP+l5ZoPNlUfTe3kT9DLyrkXOwFfu7/ylkK61l2kt7lDmOtARoVyJnnPnehJnXOn2twbpvLgYo+UwQzImeDGHnVtJE7a88DXNeNU18quNXXRsi5qYSZBriHpZbD9iczViPjZUMh2866f+HIZu2Ap2WDguFZa4Vf13Ww4lfLQsUsmcf+ty9SrOCFgRUknxbc1djY5AuyJwEHiEKr8Cmh87lJmhiuEKNQfvGcxChJQr0ynbiEMY1njL/4w04UveW/ATKYA9g4X6+A503z30u27zLw6p+/sYjh23m9cnXznZRESSSEJYYD2O/Dtkb2PLJLrMqnIOKLYB/oEuhJvPgnbIO5ENcs6H3ZyNWUy4cILxBPcDxvvV+oNHRSAsc5yw+R1QbAcB1wRQRC+TFteRHFliWTZPg/FWT0dzZfHcI6NNr0c5LaHsP6SPS4o6V53ZoQ6IEWYJSQhm7NL9r13RqovmjmxIacbCbDqSDkuxHOVfsAd+v6/GA91xl1gWGYKcYConV9mIeFa6/LhxBx7Y+DyceLBRtZ+T3HA5deMy77T8+kv7XTPnDWkWTZe2gWRahw43tw==
