kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    postgresql-password: AgCSzTWe7ZyCYnM6jPWpRm2qPVSvJDpALJ85hfNgf76BV5l3uQziTc75lwreOHa2zb0fr7W4zvDksRwtcsQKqEwKff96/LZIe/1qm89a2RO0otPggrFkD2Dgy68icGgYDzh52CrZnQvsR6NfKskNECqaeW06WOJQwomaJkyhb9Vo057Vz7gj0JoRmYzBijNdw3UQrNH1Yez2el1/vIL8nRsV/NQ0EwTtAvTGceKdPIZw22EdvciASUnY0XL13ffyS5yXw2y98s7SIfLCVerhVG+8gP1FCa8KinuKyFY3Ctt6wP2DEdNikuyqTIAwUzSdkGvbNEoB1UXuEIM1wmyePRIRwRAvGDrLbB+BGycKNk+MfgKXbsgXpHDrh7doyS+vUloUDq/8+p3c41L/y6KA/SjcVuDzUWnXYT5hmUYnbl2LxTZYkefsU/CzGu0IRDci1vWcOlEFptGXeDzmkuMoP+NZYRug3tv2MVxAKe0edS0OaPLXKBqfcEmriDpTdkf3lJJ75lda3iP3qSceS3edOx4Z3XKehm/LbrNRdOYaF2sxiPwLkkDykudtgUe7DU63pUu8zWTmt1kjo5j7xBIVwQ7Eyz+muW3YaCoedSqAmTeUB5s4NI+uonLBp7Ocscm+UKNAcljP5h1xMp6y7TVRch2W7593+2mJVoRanN5bKh7TjK9HmAIv7aEouZcyGhdr841mH1qOmeA6VCSP7SO/6IHKbV8KDfXflYGS7T33avTftw==
    postgresql-postgres-password: AgA+JWzv+m7T/TXHKtrAFzG71HahpnUiJt5BgKOR6oa2WIq/+gJWSubX0Q9fFnUydA5mMpVKK4JX0V0ijWi6LRjiUQkjQxVaIWpl0JtLNuIQdJKjkfWXXu19TByx1xVwJsvjF9QQplHxK5ovuN+WIRc2QYmH5qU5PmyLLB2Yy2KCWIjrKE1rCCbgj10w54Lci+/xWFw1GslDN91sh/lyuK2bh7oUoZHTRg/1TjE0Em7ITVVmXZxXIuX6v20Swu1Yf2MU/z4lLCUpPUAK/bWhl97BKsTPDwETXzh+2AAhQKdBYfpBnW/FA3qUn9S0Q1LHN+l6/MxZCQXNDCgXllEom209qDhBP8opVbmhcUR+4iUQR7ObWxrqyCIIYOyNXlqq88t7pF/ujyD7jabsbECE3zDlViw+auIw6sZ/MWWOaRXWLWZzWHsxjCf75DLUfmDktSNxs763I23ZYbLPRIqvAlc/fJzMengM3a9x6fXXDSZ8uzYV7wFTvccr64OS2okuC8wX1QVN0ZxPINTUGhPDsht/qCqnlgqmR5g+F9mqzw/vSwMxxRKX3/I+curRoG+7ZV/haY0r9hcdDhCjJC+Sb+WWbwGA4slyFnNJPzI08A4Hz9uPCt/rhyIQmcxFvLcbnoNSreowzKU9wn2uD+r8LrzvdiS9rTTwXee/71prc9O8biVFCroqIBeNigeONK1eWpfxqW417Z7Kh22YQQv1hCTyf1ET+PjgftLGleQhemc1Ew==
