kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgARcQCqhaeJ22vpIOOVbhtoM63ZEDRf1bTJrFAdASj8nq/AuNVE1mSh4nYC7YwQ03+tcnhV07PAjmF7wFE76lodnHvtkgJTVlbndxcj0/zCarMCqrL5/SxVzeKJSzI6ex5O1J3y0IrLQ/owfpoeme78c6d/KtBPIRUyoDvPaklkR1XtRZjVgqpoG3jum58NepfYkkFy3G/4jEccCN+imwhUnLAetutNtc09rMYZJRNC9PluDGqlAET8CEw9UI4Q8gm5hi7TEngy9AKo7T7wG/lrO8IIh+VUmR0EkzbZYVM5aknYO4C34BSNL46yAeefun5X1MS0tndNvmWxZWpWqaJEq69iZY5GVRoH1s3ClhmydzJgkbRjGYhWvVm3EJhVuMgnMTr18fDzzQhfK4Fk91stE/Zcaty8CR7s4Nf0El60KDr+h9PZxJYDNIAWPeLMOjOR5BnCbvQm3amhHHWxVqrjrK/PZt6NDdhSbTxHdHWLcP6VnshbkkshDWcNH3IEBKiX/YRz0sMxy5iRZfdjQEZRINXEPhytgWP0Ff3pX0L+lsjTkpUYhspbNYiPCLxbQCwvsgaVgbYZpnToHeDhznH/J59vHmLHnBgf42TuKvQexuhdiLQy7loVIGuHj1sX2AcLA9IKS53fp8lorG/TZk1xByNbaXqIPNmb6opb9t3SPTIfoW2ywsH4CbWd2CNWp3Ge8aYl
    admin-user: AgBXd4hINDyFwx0vFJ9Ojfm2x3AOCpN4IhFNd8B3eBbvWG4+Bhp7nB0qOZ0aYWPMpgxWXSskTpw+Z4MdmvzHijUl3loO3CFhvYnfb71QYIAL/6Oxd2yXO9ARktBIFTbrPL45jTiePN5bCeqpFLNv6mNUEt7vzB9YA/0gQnlsGMaX2CxEFfsUOUvP5yo4tgNW9Y9/gcKXd2vtEBeGjuy860MHGTxKvqlLxE91hOUDCsK01aiMMkVS4F8GWwkE0doOQzMG2eLDTwWBVEqQboxLiGTcIZfcU8iFdc5aKWD5epzkAOD/oIN1EIByx/jM8Y5sMvV3aq9rBVEKR2mLTf08hYklA9wT+T/nyrQTamf2Udl9ty/u5UenfIXNL4f0TNu4M7euxm1nrIzg2QTBfwAJahvKBus97P32FN9UQnPTBzlr9Lg7XnSO5IBybw9GVUfPDljHZkxNxskfQZ5aFlIo/7lwnJRFQmMQdvED0iIZxHeGoJT5LjjXZTsd0evmD6ItP+cfXT/K9Br6CdDasFmbzGD344yKnVhxBawRdsdDnvZidV2YcDRL7YcBGY9Hq+z++BE8tigKcseSiScRpptq+jcGmygDejbWTBQXFd3MOpTCOPxdClkYVGGYSHowNUpRO+uXCzdFEgBx6rHsKaei2rAi9va/MJ/JHjNgE+fv2Nbr34ECWMs9k+A+mLtQlqC5YXCywxTGVw==
