kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgAQ87tSniACKU3WDjuDFteBh7Ffn/8IgS2S7GR5v937hUCft+x3v4fxvR7k9nTOyZ90ZENT7knpjJUZXDMr2T54rEvMQ8dJZHY/cEFyOSZpbATigF7ZKFSvAwnpMXToxDoHv+6qhHSiMlEVb/nPPNXie6ByN6Twncw5GtU8sSADTbffgCc0z+QAlzm8qIq6C272s1djsADeZ5PcU890qXtADgL4BL5qfrQAGck5pNsBbOyCm5OMw5lw2ca30RY8IXIRm1Tou0vGaco5GidV6M56MLfv6xoBrcsWL6PlTQodpdd/jcGV6wPqtx6fFwD6FJnvCyCxn0VlnDVeVkco1c5gqKLTYP1CbYFcoMk5/ivNq474YBeyhpAaGXCDV6izLJqbjhNbBy2uWY+SIrvg+y5QA2Y1+WZId7mVNJ2oZMWWfOP4c388vkC8W1kIot6CAAoMaMb2RwuDr3N0K/QOJTPRAbwzqI7EjzK3b+RxuszDucdU0cn2MFXigjGqntzwkVqdt9BzJIjqQNRbpbYFhyDl4hFm0vZxxvbgx9Y4vsqb7PPcOc+7BuzkLwIZfFUSV+nchQDQe+M1Z79C3pepKvTQKwSTWeNSSsaFJu+UGYeXk0cQGeLGW7gIT9UZlZ3PXQskkcDa1ZLTae3Y61KGTFTftMJr5SCEzdI+cnsXbIAiJkZxUi4pBzU1dgqVcXBSwgjukeum
    admin-user: AgCvHFR6Yyhpsqkc1NkA2SWzGVhw25ZGWfeBjn97EEolOdNahsOVW8gF4HYAcnwQ+lFzIq9p+GDt0hY/Fv9hclLkeVhfHeq5wyCDRx6/Z6OFtbWC5AhZ2654h/ziyK0GLvwyLGkqQXcvmh7GrQWTFvTsk/wHDaopmTQ4Du7z2+4Ki9zdqt2WA4F4guz05tfdb/Lxfl44WpmN9WgQJREti99darNEvlgQk7v9z2B7wPqu0CxxMg18WZ5/lEP/igT84CeltYS6UIwrACI0ydqe7KRCQic9wS7G5DI34WRjEcbClxtS532nkW9YIYBeujvW8fPBEafsA2d3j0QL4iLserAxPxE/JiETChyPVZdwHEWcqhbcOfQLGiJ2skf9fJLamQLXeEhnBiep8fV+x9d3RCc4qm/vr5m4XThWjm1Bt7w7UEEowK/KJbKOjgWfSNRb2PCV4LrTpUjp8azBcI6gzw/YgLNUDyjjA6TLPfoaKSCC/D/Pq4iScPAT5ZL90D2oj2W8UjxMgNMkCHORd382yYCci2qDCUBjSNNd4auhU8e7xHECjZOaQUTXi51u+EvzogLDtgeUHpTLfmasyySVXrjoSyx32FpolsSZymg7c7h6/CCp8TC/mF58OSr8ZRiT1TNoi1AA1z38P3UREhO9dyj4PzFLza7yv8o9dIcja3F+c0DiJZXwRzuW7N4rq3tedkajfTMIHg==
