kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgBww0FcGeztFyvi/WsmoE3uDlCzTnZt6d1vfIKQeAPOtUTAII2EYgtk3XT0oiwOGI/QCfsmfI/0Ee9E41hcnHz1jw8Wb1/J7DBQxBsonVhBNOji/gktDzHyXI+LkC11/EQLnvdp7O0Ju96hhwuJL8yO4688+xkrbDSSQ8DNXybodtUKO4AUz3gGShH4JbBRuBHNV06FOvDI07Zt/l/Iuo9BxgeKhy1wEgLiFyubE8t1szYTd50piNGcPZLYIbvs+2y5+q30QnC9vBxQ8WQPxUrO3dtOGlbS/0nzXv0NUUFi53d8OCXLUX/Qup4FyeVAafjQqbsqny2HCiKEzWrMRnFOR6NFJCYgr+eTSwywpLB10PkEb1h7bqPR2hdYEbR2b6qVIkRvNim9sgwFrqAr/UQK87Fow2XxbOAs+ePvRsR86J5YnsZt/TYN2tDDgVJX6F+ppxHN8ggQ3TaE4hVxgJSa3wu/Zn5uD9NczsKRGLC/DOBO2ircBLMXv6I4hxyOpYf4HziXMUhYTyxuZeXQMM31rrEdIESRYSR5aXIsntvBgfl2U0XQ4qCVwdrEtbtJ2Ijw6N6OflBw0TC2vqlpxguc3fBD7TntWREb6SNw0uG9/QfZlIG4y/REcKzwDtRp7oZ3bQ1t6l24m23k4Huf/3cSbWgNi150Vd8EgFynDrd0vSDSdx9/4c2zY3Tfnsn5mDY524TT
    admin-user: AgB83/gnoFp04Bc0AF6dJhdPThVytg1VnKs/ZafK5FFi93iTDKUH4ZNQvT6NyiPne5gyY/dfRSPmpV2h6CIniGzBAjHbdFVpfL16RX3R0OtUd4gyvBvxw4wKQKguDKiAu3ItdKYLLYYFK+NgFJDSixYaWiwGTp48r2xxAs2qfFa+Xk58KAkDFZXF4oJ2sFEMTf7HJl70htkSIcBk4rNeQdjy7N6PidgaQiibAuLOxuDtGKppmf1XtUgIfPsM6cW5oB6WK8nQwTiGW0GEKrZ3RhOPLFOBcmZtSj+w4jRc19OVdktmvOvEE7I7Isq55x0mUCbmSKCcI8FVxF3uATR/bpZxUpHk0NZMBO2bPk6tDdHTeK0sWTgcSs1P378pq2I6ahMGUjaXY5+uGJIqcgHvDG9CpYbv0JaYMZbPTtmbzOCXOcfCxv294nsvZSBilSlVM//tQ32udYCv9Yf7yhUWBtn/9AupOcndBmQdvsstdkvWjL3oOM+VBh25WA5sr+S8OvX38gy4rNq7ltK7Rdvte4+CQXTrVpKaQMoEwWdeNFa7BRKlbwzKitxYvNEqVL3OtqgjP2Rjk966bATyCsUk5vgNLmbv6yUYj9H0LWX/y7fnMQd+dgJN+5PssVvE+yeA5u0c5/oHrNh3yVeJbLfKoeETS7cQ6KvCc0lGFbQ1I8u/LfXoOwa/9zCxw1H6k4yAZEXGnadKSg==
